/**
 * Shared logic for creating an inquiry case (status='inquiry') from inbound
 * sources (the public consult form, the admin SEAK-style portal-invite tool).
 *
 * Single source of truth for:
 *   - find-or-create attorney contact
 *   - insert into `cases` with the right defaults
 *   - link the contact via `case_contacts` in the role the caller supplies
 *
 * The previous design split this between /api/portal/consult (which wrote to
 * a separate `consultation_requests` table) and /api/portal/inquiry (which
 * wrote to `cases`). Now both flow through here.
 */

import type { getSupabaseAdmin } from './supabase-admin'
import { findContactIdByEmail, normalizeEmail } from './contacts'
import { resolveInquiryContactRole } from './constants'

type SupabaseAdmin = ReturnType<typeof getSupabaseAdmin>

export interface FindOrCreateAttorneyContactInput {
  firstName: string
  lastName: string
  email: string
  phone?: string | null
  organizationName?: string | null
}

/**
 * Look up an existing active attorney contact by email; create one if missing.
 * Returns the contact id.
 */
export async function findOrCreateAttorneyContact(
  supabase: SupabaseAdmin,
  input: FindOrCreateAttorneyContactInput,
): Promise<string> {
  const email = normalizeEmail(input.email)

  const existingId = await findContactIdByEmail(supabase, email, { activeOnly: true })
  if (existingId) return existingId

  const { data: created, error } = await supabase
    .from('contacts')
    .insert({
      contact_type: 'attorney',
      first_name: input.firstName,
      last_name: input.lastName,
      email,
      phone_primary: input.phone || null,
      organization_name: input.organizationName || null,
    })
    .select('id')
    .single()

  if (error || !created) {
    throw new Error(`Failed to create contact: ${error?.message || 'unknown error'}`)
  }
  return created.id as string
}

export interface CreateInquiryCaseInput {
  contactId: string
  firstName: string
  lastName: string
  organizationName?: string | null
  caseDescription?: string | null
  caseType?: string | null
  specialtyArea?: string | null
  side?: string | null
  requestedTurnaround?: string | null
  source?: string | null
  /**
   * Role to link the contact under, from INQUIRY_CONTACT_ROLES. Anything
   * unrecognised — including a missing value — resolves to 'other'.
   */
  role?: string | null
  /** Extra metadata to merge into `inquiry_metadata`. */
  metadata?: Record<string, unknown>
}

export interface CreateInquiryCaseResult {
  caseId: string
  caseNumber: string
}

/**
 * Insert a `cases` row with status='inquiry' and link the contact in the role
 * the caller supplied. The case_number is auto-generated by the DB trigger.
 */
export async function createInquiryCase(
  supabase: SupabaseAdmin,
  input: CreateInquiryCaseInput,
): Promise<CreateInquiryCaseResult> {
  const caseName = input.organizationName
    ? `${input.lastName} — ${input.organizationName}`
    : `${input.firstName} ${input.lastName}`

  const inquiryMetadata = {
    review_state: 'new',
    ...(input.metadata || {}),
  }

  const { data: newCase, error: caseErr } = await supabase
    .from('cases')
    .insert({
      case_name: caseName,
      case_type: input.caseType || 'other',
      // Left NULL when the inquirer did not say. The public consult form makes
      // "Retaining Side" optional, and defaulting a blank answer to 'plaintiff'
      // silently mislabels every defence inquiry that skipped the field. `side`
      // feeds conflict checks and report headers, so an unknown side stays
      // unknown until counsel supplies it. The column is nullable.
      side: input.side || null,
      specialty_area: input.specialtyArea || null,
      status: 'inquiry',
      priority: 'normal',
      date_of_referral: new Date().toISOString().split('T')[0],
      brief_summary: input.caseDescription || null,
      requested_turnaround: input.requestedTurnaround || null,
      inquiry_source: input.source || 'direct',
      inquiry_metadata: inquiryMetadata,
    })
    .select('id, case_number')
    .single()

  if (caseErr || !newCase) {
    throw new Error(`Failed to create inquiry case: ${caseErr?.message || 'unknown error'}`)
  }

  // `is_primary` stays true regardless of role: this contact is the person the
  // matter came in through and the one to reply to, which is a separate
  // question from whether they are retaining counsel. Case EW-2026-0035 is the
  // pattern — the referring nurse-consultant is primary with role 'other',
  // while the actual retaining attorney is a different contact entirely.
  const { error: linkErr } = await supabase
    .from('case_contacts')
    .insert({
      case_id: newCase.id,
      contact_id: input.contactId,
      role: resolveInquiryContactRole(input.role),
      is_primary: true,
    })

  if (linkErr) {
    // Non-fatal: case exists, link can be added manually
    console.error('[inquiry-helpers] case_contacts link failed:', linkErr)
  }

  return {
    caseId: newCase.id as string,
    caseNumber: newCase.case_number as string,
  }
}
