/**
 * Shared logic for creating an inquiry case (status='inquiry') from inbound
 * sources (the public consult form, the admin SEAK-style portal-invite tool).
 *
 * Single source of truth for:
 *   - find-or-create attorney contact
 *   - insert into `cases` with the right defaults
 *   - link the contact via `case_contacts` as retaining_attorney
 *
 * The previous design split this between /api/portal/consult (which wrote to
 * a separate `consultation_requests` table) and /api/portal/inquiry (which
 * wrote to `cases`). Now both flow through here.
 */

import type { getSupabaseAdmin } from './supabase-admin'

type SupabaseAdmin = ReturnType<typeof getSupabaseAdmin>

export interface FindOrCreateAttorneyContactInput {
  firstName: string
  lastName: string
  email: string
  phone?: string | null
  organizationName?: string | null
}

/**
 * Look up an existing active attorney contact by email; create one if missing.
 * Returns the contact id.
 */
export async function findOrCreateAttorneyContact(
  supabase: SupabaseAdmin,
  input: FindOrCreateAttorneyContactInput,
): Promise<string> {
  const { data: existing } = await supabase
    .from('contacts')
    .select('id')
    .eq('email', input.email)
    .eq('is_active', true)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (existing?.id) return existing.id as string

  const { data: created, error } = await supabase
    .from('contacts')
    .insert({
      contact_type: 'attorney',
      first_name: input.firstName,
      last_name: input.lastName,
      email: input.email,
      phone_primary: input.phone || null,
      organization_name: input.organizationName || null,
    })
    .select('id')
    .single()

  if (error || !created) {
    throw new Error(`Failed to create contact: ${error?.message || 'unknown error'}`)
  }
  return created.id as string
}

export interface CreateInquiryCaseInput {
  contactId: string
  firstName: string
  lastName: string
  organizationName?: string | null
  caseDescription?: string | null
  caseType?: string | null
  specialtyArea?: string | null
  side?: string | null
  requestedTurnaround?: string | null
  source?: string | null
  /** Extra metadata to merge into `inquiry_metadata`. */
  metadata?: Record<string, unknown>
}

export interface CreateInquiryCaseResult {
  caseId: string
  caseNumber: string
}

/**
 * Insert a `cases` row with status='inquiry' and link the contact as the
 * retaining attorney. The case_number is auto-generated by the DB trigger.
 */
export async function createInquiryCase(
  supabase: SupabaseAdmin,
  input: CreateInquiryCaseInput,
): Promise<CreateInquiryCaseResult> {
  const caseName = input.organizationName
    ? `${input.lastName} — ${input.organizationName}`
    : `${input.firstName} ${input.lastName}`

  const inquiryMetadata = {
    review_state: 'new',
    ...(input.metadata || {}),
  }

  const { data: newCase, error: caseErr } = await supabase
    .from('cases')
    .insert({
      case_name: caseName,
      case_type: input.caseType || 'other',
      side: input.side || 'plaintiff',
      specialty_area: input.specialtyArea || null,
      status: 'inquiry',
      priority: 'normal',
      date_of_referral: new Date().toISOString().split('T')[0],
      brief_summary: input.caseDescription || null,
      requested_turnaround: input.requestedTurnaround || null,
      inquiry_source: input.source || 'direct',
      inquiry_metadata: inquiryMetadata,
    })
    .select('id, case_number')
    .single()

  if (caseErr || !newCase) {
    throw new Error(`Failed to create inquiry case: ${caseErr?.message || 'unknown error'}`)
  }

  const { error: linkErr } = await supabase
    .from('case_contacts')
    .insert({
      case_id: newCase.id,
      contact_id: input.contactId,
      role: 'retaining_attorney',
      is_primary: true,
    })

  if (linkErr) {
    // Non-fatal: case exists, link can be added manually
    console.error('[inquiry-helpers] case_contacts link failed:', linkErr)
  }

  return {
    caseId: newCase.id as string,
    caseNumber: newCase.case_number as string,
  }
}
