import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'

/**
 * POST /api/inquiries/[id]/convert
 * Converts a consultation_requests row into a real `cases` row.
 * - Reuses the inquiry's contact (or creates one if missing).
 * - Links the contact to the new case as retaining counsel.
 * - Stamps the inquiry with case_id + converted_at and flips status to 'converted'.
 *
 * Intended to be called from the protected Inquiries admin page after a
 * phone call confirms the engagement. Authorization: this sits behind the
 * protected (auth) route group via the admin UI; the endpoint itself is
 * not public-facing but validates the inquiry state before writing.
 */
export async function POST(_request: NextRequest, context: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await context.params
    if (!id) return NextResponse.json({ error: 'Missing inquiry id' }, { status: 400 })

    const supabase = getSupabaseAdmin()

    // 1. Load inquiry
    const { data: inquiry, error: loadErr } = await supabase
      .from('consultation_requests')
      .select('*')
      .eq('id', id)
      .single()

    if (loadErr || !inquiry) {
      return NextResponse.json({ error: 'Inquiry not found' }, { status: 404 })
    }

    if (inquiry.status === 'converted' && inquiry.case_id) {
      return NextResponse.json({
        success: true,
        alreadyConverted: true,
        caseId: inquiry.case_id,
      })
    }

    // 2. Resolve contact
    let contactId: string | null = inquiry.contact_id
    if (!contactId) {
      const { data: existing } = await supabase
        .from('contacts')
        .select('id')
        .eq('email', inquiry.email)
        .eq('is_active', true)
        .limit(1)
        .maybeSingle()

      if (existing) {
        contactId = existing.id
      } else {
        const { data: newContact, error: contactErr } = await supabase
          .from('contacts')
          .insert({
            contact_type: 'attorney',
            first_name: inquiry.first_name,
            last_name: inquiry.last_name,
            email: inquiry.email,
            phone_primary: inquiry.phone || null,
            organization_name: inquiry.organization_name || null,
          })
          .select('id')
          .single()

        if (contactErr || !newContact) {
          console.error('Contact creation error:', contactErr)
          return NextResponse.json({ error: 'Failed to create contact' }, { status: 500 })
        }
        contactId = newContact.id
      }

      // Backfill inquiry.contact_id for future lookups
      await supabase
        .from('consultation_requests')
        .update({ contact_id: contactId })
        .eq('id', id)
    }

    // 3. Create case — case_number is auto-generated by DB trigger
    const caseName = inquiry.organization_name
      ? `${inquiry.last_name} — ${inquiry.organization_name}`
      : `${inquiry.first_name} ${inquiry.last_name}`

    const { data: newCase, error: caseErr } = await supabase
      .from('cases')
      .insert({
        case_name: caseName,
        case_type: inquiry.case_type || 'other',
        specialty_area: inquiry.specialty_area || null,
        side: inquiry.side || 'plaintiff',
        status: 'inquiry',
        priority: 'normal',
        date_of_referral: new Date().toISOString().split('T')[0],
        brief_summary: inquiry.case_description || null,
      })
      .select('id, case_number')
      .single()

    if (caseErr || !newCase) {
      console.error('Case creation error:', caseErr)
      return NextResponse.json({ error: 'Failed to create case' }, { status: 500 })
    }

    // 4. Link contact to case as retaining counsel
    if (contactId) {
      const { error: linkErr } = await supabase
        .from('case_contacts')
        .insert({
          case_id: newCase.id,
          contact_id: contactId,
          role: 'retaining_attorney',
          is_primary: true,
        })
      if (linkErr) {
        console.error('Case-contact link error:', linkErr)
        // Not fatal — case exists, link can be added manually
      }
    }

    // 5. Mark inquiry converted
    await supabase
      .from('consultation_requests')
      .update({
        status: 'converted',
        case_id: newCase.id,
        converted_at: new Date().toISOString(),
      })
      .eq('id', id)

    return NextResponse.json({
      success: true,
      caseId: newCase.id,
      caseNumber: newCase.case_number,
    })
  } catch (err) {
    console.error('Inquiry convert error:', err)
    return NextResponse.json({ error: 'Convert failed' }, { status: 500 })
  }
}
