import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import { Resend } from 'resend'
import crypto from 'crypto'
import { caseEmailHeaders, caseEmailSubject } from '@/lib/email-threading'
import { EMAIL_BCC, EMAIL_REPLY_TO } from '@/lib/email-config'
import { wrapEmail, htmlToText } from '@/lib/email-templates'

// POST: Create an inquiry portal — contact, case, link, invite, and email in one shot
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { firstName, lastName, email, organizationName, invitationMessage } = body

    if (!firstName || !lastName || !email) {
      return NextResponse.json(
        { error: 'Missing required fields: firstName, lastName, email' },
        { status: 400 }
      )
    }

    const supabase = getSupabaseAdmin()

    // 1. Check for existing contact with same email to avoid duplicates
    let contactId: string
    const { data: existingContact } = await supabase
      .from('contacts')
      .select('id')
      .eq('email', email)
      .eq('is_active', true)
      .limit(1)
      .single()

    if (existingContact) {
      contactId = existingContact.id
    } else {
      const { data: newContact, error: contactError } = await supabase
        .from('contacts')
        .insert({
          contact_type: 'attorney',
          first_name: firstName,
          last_name: lastName,
          email,
          organization_name: organizationName || null,
        })
        .select('id')
        .single()

      if (contactError || !newContact) {
        console.error('Contact creation error:', contactError)
        return NextResponse.json({ error: 'Failed to create contact' }, { status: 500 })
      }
      contactId = newContact.id
    }

    // 2. Create minimal inquiry case (case_number auto-generated by DB trigger)
    const { data: newCase, error: caseError } = await supabase
      .from('cases')
      .insert({
        case_name: `Inquiry — ${firstName} ${lastName}`,
        case_type: 'other',
        side: 'plaintiff',
        status: 'inquiry',
        priority: 'normal',
        date_of_referral: new Date().toISOString().split('T')[0],
      })
      .select('id, case_number')
      .single()

    if (caseError || !newCase) {
      console.error('Case creation error:', caseError)
      return NextResponse.json({ error: 'Failed to create case' }, { status: 500 })
    }

    const caseNumber = newCase.case_number

    // 3b. Send new-case notification to Dr. Ettinger — THREAD ROOT for the case
    const resendKey = process.env.RESEND_API_KEY
    if (resendKey) {
      const caseName = `Inquiry — ${firstName} ${lastName}`
      const notifyAppUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://expert-witness.vercel.app'
      const rootSubject = caseEmailSubject(caseNumber, caseName, true)
      const rootHeaders = caseEmailHeaders(newCase.id, { isRoot: true })
      fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${resendKey}` },
        body: JSON.stringify({
          from: 'Mark Ettinger, M.D. <mark@markettingermd.com>',
          to: 'markettingermd@gmail.com',
          subject: rootSubject,
          headers: rootHeaders,
          html: `
            <div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto;">
              <div style="background-color: #0E1F35; color: white; padding: 24px 32px;">
                <h1 style="margin: 0; font-size: 20px; color: #DFC06A;">New Inquiry Case</h1>
              </div>
              <div style="padding: 32px; border: 1px solid #e5e7eb; border-top: none;">
                <p style="color: #374151; font-size: 15px; line-height: 1.6;">
                  A portal invite was sent to <strong>${firstName} ${lastName}</strong>${organizationName ? ` (${organizationName})` : ''} at <strong>${email}</strong>.
                </p>
                <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                  <tr><td style="padding: 8px 0; color: #6b7280; font-size: 14px; width: 120px;">Case:</td><td style="padding: 8px 0; font-size: 14px; font-weight: 600;">${caseName}</td></tr>
                  <tr><td style="padding: 8px 0; color: #6b7280; font-size: 14px;">Number:</td><td style="padding: 8px 0; font-size: 14px;">${caseNumber}</td></tr>
                </table>
                <div style="text-align: center; margin: 28px 0;">
                  <a href="${notifyAppUrl}/cases/${newCase.id}" style="display: inline-block; background-color: #0E1F35; color: white; text-decoration: none; padding: 12px 32px; border-radius: 6px; font-size: 14px; font-weight: 600;">View Case</a>
                </div>
              </div>
            </div>`,
        }),
      }).catch(err => console.error('Inquiry notification email error:', err))
    }

    // 4. Link contact to case
    const { error: linkError } = await supabase
      .from('case_contacts')
      .insert({
        case_id: newCase.id,
        contact_id: contactId,
        role: 'retaining_attorney',
        is_primary: true,
      })

    if (linkError) {
      console.error('Case-contact link error:', linkError)
    }

    // 5. Create portal invite with inquiry onboarding steps
    const token = crypto.randomBytes(32).toString('hex')
    const expiresAt = new Date()
    expiresAt.setDate(expiresAt.getDate() + 90)

    const onboardingSteps = {
      review_fee_schedule: 'pending',
      review_cv: 'locked',
      enter_case_details: 'locked',
      invite_colleague: 'locked',
      schedule_call: 'locked',
      sign_contract: 'not_applicable',
      retainer_payment: 'not_applicable',
      upload_documents: 'locked',
    }

    const { data: invite, error: inviteError } = await supabase
      .from('portal_invites')
      .insert({
        case_id: newCase.id,
        contact_id: contactId,
        token,
        onboarding_mode: true,
        onboarding_steps: onboardingSteps,
        can_view_summary: true,
        can_view_timeline: true,
        can_message: true,
        can_view_reports: false,
        can_edit_reports: false,
        can_upload_documents: true,
        can_view_fee_schedule: true,
        can_view_depositions: false,
        can_view_billing: false,
        can_book_scheduling: true,
        can_sign_contract: false,
        can_invite_contacts: true,
        invitation_message: invitationMessage || null,
        expires_at: expiresAt.toISOString(),
      })
      .select('id')
      .single()

    if (inviteError || !invite) {
      console.error('Portal invite creation error:', inviteError)
      return NextResponse.json({ error: 'Failed to create portal invite' }, { status: 500 })
    }

    // 6. Send inquiry email directly via Resend (not via internal fetch)
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://expert-witness.vercel.app'
    const portalUrl = `${appUrl}/portal/${token}`

    try {
      const resend = new Resend(process.env.RESEND_API_KEY)
      const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'Dr. Mark Ettinger <onboarding@resend.dev>'
      const recipientName = `${firstName} ${lastName}`
      const greeting = `Dear ${recipientName},`

      const features = [
        'Review fee schedule and rates',
        'Review qualifications and curriculum vitae',
        'Provide case details for initial evaluation',
        'Schedule a consultation call',
      ]

      const featureListHtml = features
        .map((feature) => `<li style="margin: 3px 0;">${feature}</li>`)
        .join('')

      const personalMessageHtml = invitationMessage
        ? `<p style="margin: 16px 0; padding: 10px 14px; background: #f7f8fa; border-left: 3px solid #DFC06A; font-style: italic; color: #44403c;">&ldquo;${invitationMessage}&rdquo;<br><span style="font-style: normal; font-size: 13px; color: #6B7280;">&mdash; Mark Ettinger, M.D.</span></p>`
        : ''

      const htmlBody = wrapEmail({
        subject: 'Expert Witness Consultation — Dr. Mark Ettinger',
        previewText: 'Review qualifications and fee schedule for an anesthesiology expert engagement',
        heading: 'Expert Witness Consultation',
        bodyHtml: `
          <p>${greeting}</p>
          <p>Thank you for your interest. I would like to invite you to review my qualifications and fee schedule for a potential expert witness engagement in anesthesiology.</p>
          ${personalMessageHtml}
          <p style="margin: 16px 0 4px; font-weight: 600; color: #0E1F35;">Getting started:</p>
          <ul style="margin: 4px 0 0; padding-left: 20px; line-height: 1.7;">${featureListHtml}</ul>
        `,
        ctaLabel: 'Get Started',
        ctaUrl: portalUrl,
        footerNote: 'This link is private and unique to you. Please do not share it.',
      })

      const inviteSubject = caseEmailSubject(caseNumber, `Inquiry — ${firstName} ${lastName}`, true)
      const inviteHeaders = caseEmailHeaders(newCase.id, { selfLabel: 'invite' })

      const { error: emailError } = await resend.emails.send({
        from: FROM_EMAIL,
        to: [email],
        bcc: EMAIL_BCC,
        replyTo: EMAIL_REPLY_TO,
        subject: inviteSubject,
        headers: inviteHeaders,
        html: htmlBody,
        text: htmlToText(htmlBody),
      })

      if (emailError) {
        console.error('Resend error:', emailError)
      }
    } catch (emailError) {
      console.error('Email send error:', emailError)
      // Don't fail the whole request if email fails — portal URL still works
    }

    return NextResponse.json({
      caseId: newCase.id,
      contactId,
      portalUrl,
      caseNumber,
      inviteId: invite.id,
    })
  } catch (error) {
    console.error('Inquiry portal creation error:', error)
    return NextResponse.json({ error: 'Failed to create inquiry portal' }, { status: 500 })
  }
}
